### ISSUE TITLE
[suggestion] turn possible to write log in local disk

### ISSUE THREAD

**Issue by robsongajunior** [smallhelm/json-log#1]
Nice job!

Maybe it is interesting to have a function like: logToFile,
where you set the local file to write on disk.

**Comment by farskipper** [comment]
Thanks!
Part of the philosophy with this logger is to let the process manager write the log files. That's why there is no `logToFile` option. https://github.com/smallhelm/json-log#write-to-stdouterr

For example, what I often do is use systemd. Setup something like this: https://www.axllent.org/docs/view/nodejs-service-with-systemd/ Systemd reads the stdout/stderr and pipes it to `/var/log/syslog`

However, if you do want to write to logs in process you can do that by creating a custom logger https://github.com/smallhelm/json-log#customize
